import {useEffect,useMemo,useRef,useState} from 'react'
import {categories,products,type Category,type Product} from './catalog'
import {clearLocalData,createFictionalOrder,loadCart,PAYABLE_TOTAL,pickStoryId,saveCart,type Cart} from './cart'
import {copies,currencyOptions,formatMoney,localeOptions,productCopy,type Currency,type Locale} from './i18n'
import {loadPreferences,savePreferences} from './preferences'

function ProductImage({product,name}:{product:Product;name:string}){return <div className="product-image"><img src={product.image} alt={name} loading="lazy"/></div>}

export default function App(){
 const initial=loadPreferences()
 const [locale,setLocale]=useState<Locale>(initial.locale),[currency,setCurrency]=useState<Currency>(initial.currency)
 const [cart,setCart]=useState<Cart>(loadCart),[drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false),[complete,setComplete]=useState(false),[story,setStory]=useState(0),[category,setCategory]=useState<Category|'all'>('all'),[query,setQuery]=useState(''),[toast,setToast]=useState(''),[ack,setAck]=useState(false),[district,setDistrict]=useState(''),[selected,setSelected]=useState<Product|null>(null)
 const closeRef=useRef<HTMLButtonElement>(null),t=copies[locale],money=(value:number)=>formatMoney(value,currency,locale)
 useEffect(()=>saveCart(cart),[cart])
 useEffect(()=>{savePreferences({locale,currency});document.documentElement.lang=locale},[locale,currency])
 useEffect(()=>{if(drawer)closeRef.current?.focus()},[drawer])
 useEffect(()=>{const handle=(event:KeyboardEvent)=>{if(event.key==='Escape'){setDrawer(false);setCheckout(false);setComplete(false);setSelected(null)}};addEventListener('keydown',handle);return()=>removeEventListener('keydown',handle)},[])
 const items=useMemo(()=>products.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]})),[cart])
 const count=items.reduce((sum,p)=>sum+p.quantity,0),subtotal=items.reduce((sum,p)=>sum+p.price*p.quantity,0)
 const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase(locale);return products.filter(product=>{const localized=productCopy(product,locale);return (category==='all'||product.category===category)&&(!term||[localized.name,localized.secondary,localized.description,t.categoryNames[product.category],...product.aliases].some(value=>value.toLocaleLowerCase(locale).includes(term)))})},[category,locale,query,t.categoryNames])
 const add=(product:Product)=>{setCart(current=>({...current,[product.id]:Math.min((current[product.id]??0)+1,20)}));setDrawer(true);setToast(t.added);setTimeout(()=>setToast(''),2000)}
 const update=(id:string,change:number)=>setCart(current=>{const next={...current},quantity=(next[id]??0)+change;if(quantity<=0)delete next[id];else next[id]=Math.min(quantity,20);return next})
 const choose=(next:Category)=>{setCategory(next);setQuery('');document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'})}
 const changeLocale=(next:Locale)=>{setLocale(next);setQuery('');setCategory('all');setDistrict('')}
 const finish=()=>{if(!ack)return;const nextStory=pickStoryId(t.deliveryStories.length);createFictionalOrder(cart,subtotal,district,nextStory);setStory(nextStory);setCart({});setCheckout(false);setComplete(true);setAck(false)}
 const reset=()=>{clearLocalData();setCart({});setLocale('zh-HK');setCurrency('HKD');setDrawer(false);setToast(t.cleared)}
 return <div className="app">
  <a className="skip-link" href="#shop">{t.skip}</a><div className="notice"><span>✦</span>{t.announcement}<span>✦</span></div>
  <header className="header"><a className="logo" href="#top"><span className="logo-orbit"><i>✦</i></span><span>little orbit<small>小小宇宙</small></span></a><nav><a href="#shop">{t.shop}</a><a href="#story">{t.story}</a><a href="#faq">{t.faq}</a></nav><div className="site-controls"><label><span className="sr-only">Language</span><select value={locale} onChange={event=>changeLocale(event.target.value as Locale)} aria-label="Language">{localeOptions.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label><label><span className="sr-only">Currency</span><select value={currency} onChange={event=>setCurrency(event.target.value as Currency)} aria-label="Currency">{currencyOptions.map(option=><option key={option}>{option}</option>)}</select></label><button className="cart-button" onClick={()=>setDrawer(true)} aria-label={t.cartLabel(count)}><span>{t.cart}</span><b>{count}</b></button></div></header>
  <main id="top"><section className="hero"><img className="hero-photo" src="/hero-nest-v3-space.png" alt=""/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">{t.heroEyebrow}</p><h1>{t.heroTitle.split('\n').map(line=><span key={line}>{line}</span>)}</h1><p>{t.heroBody}</p><div className="hero-actions"><a className="primary light" href="#shop">{t.heroCta}<span>↘</span></a><small>{t.heroNote}</small></div></div><div className="sticker"><span>LITTLE</span><b>50</b></div></section>
  <section className="promise-strip">{t.promises.map(([icon,title,body])=><div key={title}><span>{icon}</span><p><b>{title}</b><small>{body}</small></p></div>)}</section>
  <section className="intro section"><p className="eyebrow">{t.categoryEyebrow}</p><div className="section-title"><h2>{t.categories}</h2><p>{t.categoriesSub}</p></div><div className="category-grid">{categories.map((item,index)=><button key={item.name} className={`category-card category-${index}`} onClick={()=>choose(item.name)}><span className="category-orbit"><i>{item.icon}</i></span><span><b>{t.categoryNames[item.name]}</b><small>{t.categoryBlurbs[item.name]}</small><em>{t.categoryCount(item.count)}</em></span></button>)}</div></section>
  <section className="featured section"><div className="section-title"><div><p className="eyebrow">{t.featuredEyebrow}</p><h2>{t.featured}</h2></div><p>{t.featuredSub}</p></div><div className="featured-grid">{products.filter(product=>product.badge==='人氣之選').slice(0,4).map(product=>{const text=productCopy(product,locale);return <article className="featured-card" key={product.id}><button className="bare-image" onClick={()=>setSelected(product)}><ProductImage product={product} name={text.name}/></button><div><small>{t.categoryNames[product.category]}</small><h3>{text.name}</h3><p>{text.secondary}</p><button onClick={()=>add(product)}>＋ {t.add}</button></div></article>})}</div></section>
  <section className="catalog section" id="shop"><div className="catalog-top"><div><p className="eyebrow">{t.catalogEyebrow}</p><h2>{t.catalog}</h2><p>{t.catalogSub}</p></div><label className="search"><span>⌕</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.searchPlaceholder} aria-label={t.searchLabel}/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search">×</button>}</label></div><div className="catalog-tools"><div className="filters"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>{t.all}</button>{categories.map(item=><button className={category===item.name?'active':''} onClick={()=>setCategory(item.name)} key={item.name}>{t.categoryNames[item.name]}</button>)}</div><p>{t.resultCount(visible.length)}</p></div>
  {visible.length?<div className="product-grid">{visible.map(product=>{const text=productCopy(product,locale);return <article className="product-card" key={product.id}><div className="image-wrap"><button className="bare-image" onClick={()=>setSelected(product)}><ProductImage product={product} name={text.name}/></button>{product.badge&&<span className="badge">{t.badges[product.badge]}</span>}<button className="quick-add" onClick={()=>add(product)} aria-label={t.addLabel(text.name)}>＋</button></div><div className="product-info"><p className="category-label">{t.categoryNames[product.category]}</p><button className="product-name" onClick={()=>setSelected(product)}><h3>{text.name}</h3></button><p>{text.description}</p><div><span><small>{t.imaginaryPrice}</small><b>{money(product.price)}</b></span><span className="rating">★ {product.rating}</span></div></div></article>})}</div>:<div className="no-results"><span>☾</span><h3>{t.noResults}</h3><p>{t.noResultsSub}</p><button className="primary" onClick={()=>{setQuery('');setCategory('all')}}>{t.showAll}</button></div>}</section>
  <section className="story section" id="story"><div className="story-visual"><div className="big-moon">50<small>STARS</small></div><span className="orbit-line one">✦</span><span className="orbit-line two">☁</span></div><div><p className="eyebrow">{t.storyEyebrow}</p><h2>{t.storyTitle.split('\n').map(line=><span key={line}>{line}<br/></span>)}</h2><p>{t.storyBody}</p><ol>{t.storySteps.map(([title,body],index)=><li key={title}><span>0{index+1}</span><div><b>{title}</b><small>{body}</small></div></li>)}</ol></div></section>
  <section className="faq section" id="faq"><div><p className="eyebrow">{t.faqEyebrow}</p><h2>{t.faqTitle}</h2></div><div className="faq-list">{t.faqItems.map(([question,answer])=><details key={question}><summary>{question}<span>＋</span></summary><p>{answer}</p></details>)}</div></section></main>
  <footer><div className="footer-brand"><a className="logo" href="#top"><span className="logo-orbit"><i>✦</i></span><span>little orbit<small>小小宇宙</small></span></a><p>{t.footerLine}</p></div><div><b>{t.explore}</b><a href="#shop">{t.allProducts}</a><a href="#story">{t.about}</a></div><div><b>{t.yourData}</b><button onClick={reset}>{t.clear}</button><small>{t.localOnly}</small></div><span>{t.rights}</span></footer>
  {selected&&(()=>{const text=productCopy(selected,locale);return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="product-modal" role="dialog" aria-modal="true" aria-labelledby="product-title"><button className="close" onClick={()=>setSelected(null)} aria-label="Close">×</button><ProductImage product={selected} name={text.name}/><div className="product-modal-copy"><p className="eyebrow">{t.categoryNames[selected.category]}</p><h2 id="product-title">{text.name}</h2><p className="en-name">{text.secondary}</p><p>{text.description}</p><div className="modal-price"><span><small>{t.imaginaryPrice}</small><b>{money(selected.price)}</b></span><span>★ {selected.rating}</span></div><button className="primary" onClick={()=>{add(selected);setSelected(null)}}>{t.add} ＋</button></div></section></div>})()}
  {drawer&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setDrawer(false)}}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="bag-title"><div className="drawer-head"><div><p className="eyebrow">{t.drawerEyebrow}</p><h2 id="bag-title">{t.cart}<span>{count}</span></h2></div><button ref={closeRef} className="close" onClick={()=>setDrawer(false)} aria-label="Close">×</button></div><div className="cart-items">{items.length?items.map(product=>{const text=productCopy(product,locale);return <div className="cart-row" key={product.id}><ProductImage product={product} name={text.name}/><div><h3>{text.name}</h3><p>{money(product.price)}</p><div className="quantity"><button onClick={()=>update(product.id,-1)} aria-label="Decrease">−</button><span>{product.quantity}</span><button onClick={()=>update(product.id,1)} aria-label="Increase">＋</button></div></div><button className="remove" onClick={()=>update(product.id,-product.quantity)} aria-label="Remove">×</button></div>}):<div className="empty"><span>☾</span><h3>{t.empty}</h3><p>{t.emptySub}</p></div>}</div>{items.length>0&&<div className="cart-summary"><p className="cart-joke">{t.cartDisclosure}</p><dl><div><dt>{t.subtotal}</dt><dd>{money(subtotal)}</dd></div><div className="discount"><dt>{t.discount}</dt><dd>−{money(subtotal)}</dd></div><div className="grand-total"><dt>{t.total}</dt><dd>{money(PAYABLE_TOTAL)}</dd></div></dl><button className="primary checkout-button" onClick={()=>{setDrawer(false);setCheckout(true)}}>{t.checkout} →</button></div>}</aside></div>}
  {checkout&&<div className="modal-backdrop"><section className="checkout-modal" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><button className="close" onClick={()=>setCheckout(false)} aria-label="Close">×</button><p className="eyebrow">{t.checkoutEyebrow}</p><h2 id="checkout-title">{t.checkoutTitle}</h2><p className="checkout-intro">{t.checkoutIntro}</p><div className="checkout-box"><div><span>◉</span><p><small>{t.method}</small><b>ORBIT PASS •••• 0000</b></p><em>{t.displayOnly}</em></div></div><label className="district-label">{t.destination}<select value={district} onChange={event=>setDistrict(event.target.value)}><option value="">{t.destinationEmpty}</option>{t.districts.map(option=><option key={option}>{option}</option>)}</select></label><label className="ack"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/><span>{t.acknowledgement}</span></label><dl className="checkout-totals"><div><dt>{t.subtotal}</dt><dd>{money(subtotal)}</dd></div><div><dt>{t.discount}</dt><dd>−{money(subtotal)}</dd></div><div><dt>{t.total}</dt><dd>{money(PAYABLE_TOTAL)}</dd></div></dl><button className="primary order-button" disabled={!ack} onClick={finish}>{t.order}</button></section></div>}
  {complete&&<div className="modal-backdrop"><section className="success-modal" role="dialog" aria-modal="true" aria-labelledby="success-title"><div className="success-burst">✦</div><p className="eyebrow">{t.successEyebrow}</p><h2 id="success-title">{t.success}</h2><p>{t.successSub}</p><div className="timeline">{t.deliveryStories[story].map((step,index)=><p className="done" key={step}><span>{index===0?'✓':index+1}</span>{step}</p>)}</div><button className="primary" onClick={()=>setComplete(false)}>{t.continue}</button></section></div>}
  <div className={`toast ${toast?'show':''}`} role="status">{toast}</div>
 </div>
}
