import {useEffect,useMemo,useRef,useState} from 'react'
import {categories,products,type Category,type Product} from './catalog'
import {clearLocalData,createFictionalOrder,loadCart,PAYABLE_TOTAL,pickStoryId,saveCart,type Cart} from './cart'
import {zhHK as t} from './locales/zhHK'

const money=(v:number)=>new Intl.NumberFormat('zh-HK',{style:'currency',currency:'HKD',maximumFractionDigits:0}).format(v)
const deliveryStories=[['虛構落單成功','小鯨魚飛過獅子山','送達你嘅想像力'],['月球倉收到訊號','火箭排緊紅隧','星星喺維港上空簽收'],['銀包確認零反應','外星速遞員食緊菠蘿包','包裹安全抵達幻想世界']] as const
function ProductImage({product}:{product:Product}){return <div className="product-image"><img src={product.image} alt={product.name} loading="lazy"/></div>}

export default function App(){
 const [cart,setCart]=useState<Cart>(loadCart),[drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false),[complete,setComplete]=useState(false),[story,setStory]=useState(0),[category,setCategory]=useState<Category|'全部'>('全部'),[query,setQuery]=useState(''),[toast,setToast]=useState(''),[ack,setAck]=useState(false),[district,setDistrict]=useState(''),[selected,setSelected]=useState<Product|null>(null);const closeRef=useRef<HTMLButtonElement>(null)
 useEffect(()=>saveCart(cart),[cart]);useEffect(()=>{if(drawer)closeRef.current?.focus()},[drawer]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setDrawer(false);setCheckout(false);setSelected(null)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[])
 const items=useMemo(()=>products.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]})),[cart]),count=items.reduce((s,p)=>s+p.quantity,0),subtotal=items.reduce((s,p)=>s+p.price*p.quantity,0)
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return products.filter(p=>(category==='全部'||p.category===category)&&(!q||[p.name,p.enName,p.description,...p.aliases].some(x=>x.toLowerCase().includes(q))))},[category,query])
 const add=(id:string)=>{setCart(c=>({...c,[id]:Math.min((c[id]??0)+1,20)}));setDrawer(true);setToast(t.added);setTimeout(()=>setToast(''),2000)},update=(id:string,d:number)=>setCart(c=>{const n={...c},q=(n[id]??0)+d;if(q<=0)delete n[id];else n[id]=Math.min(q,20);return n})
 const choose=(c:Category)=>{setCategory(c);setQuery('');document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'})},finish=()=>{if(!ack)return;const nextStory=pickStoryId(deliveryStories.length);createFictionalOrder(cart,subtotal,district,nextStory);setStory(nextStory);setCart({});setCheckout(false);setComplete(true);setAck(false)},reset=()=>{clearLocalData();setCart({});setDrawer(false);setToast('本機資料已清除')}
 return <div className="app"><a className="skip-link" href="#shop">直接去產品</a><div className="notice"><span>✦</span>{t.notice}<span>✦</span></div>
 <header className="header"><a className="logo" href="#top"><span className="logo-orbit"><i>✦</i></span><span>little orbit<small>小小宇宙</small></span></a><nav><a href="#shop">探索宇宙</a><a href="#story">我哋嘅軌道</a><a href="#faq">常見問題</a></nav><button className="cart-button" onClick={()=>setDrawer(true)} aria-label={`購物袋，${count}件`}><span>購物袋</span><b>{count}</b></button></header>
 <main id="top"><section className="hero"><img className="hero-photo" src="/hero-nest-v3-space.png" alt="月亮、星星與柔軟嬰兒小物組成的想像宇宙"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">{t.heroEyebrow}</p><h1>{t.heroTitle.split('\n').map(x=><span key={x}>{x}</span>)}</h1><p>{t.heroBody}</p><div className="hero-actions"><a className="primary light" href="#shop">{t.heroCta}<span>↘</span></a><small>{t.heroNote}</small></div></div><div className="zero-moon"><span>永遠</span><b>$0</b></div></section>
 <section className="promise-strip"><div><span>☆</span><p><b>只係幻想</b><small>一件真貨都冇</small></p></div><div><span>0</span><p><b>永遠零蚊</b><small>加幾多都係 HK$0</small></p></div><div><span>◌</span><p><b>私隱留喺地球</b><small>唔收敏感資料</small></p></div></section>
 <section className="intro section"><p className="eyebrow">Five tiny galaxies</p><div className="section-title"><h2>{t.categories}</h2><p>{t.categoriesSub}</p></div><div className="category-grid">{categories.map((c,i)=><button key={c.name} className={`category-card category-${i}`} onClick={()=>choose(c.name)}><span className="category-orbit"><i>{c.icon}</i></span><span><b>{c.name}</b><small>{c.blurb}</small><em>{c.count} 件好物 ↗</em></span></button>)}</div></section>
 <section className="featured section"><div className="section-title"><div><p className="eyebrow">Closest to our hearts</p><h2>今週最近月亮</h2></div><p>四件小物，正喺想像力軌道上。</p></div><div className="featured-grid">{products.filter(p=>p.badge==='人氣之選').slice(0,4).map(p=><article className="featured-card" key={p.id}><button className="bare-image" onClick={()=>setSelected(p)}><ProductImage product={p}/></button><div><small>{p.category}</small><h3>{p.name}</h3><p>{p.enName}</p><button onClick={()=>add(p.id)}>＋ {t.add}</button></div></article>)}</div></section>
 <section className="catalog section" id="shop"><div className="catalog-top"><div><p className="eyebrow">All 50 imaginary things</p><h2>{t.catalog}</h2><p>{t.catalogSub}</p></div><label className="search"><span>⌕</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋月亮、鯨魚、睡衣…" aria-label="搜尋產品"/>{query&&<button onClick={()=>setQuery('')}>×</button>}</label></div><div className="catalog-tools"><div className="filters">{(['全部',...categories.map(c=>c.name)] as const).map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><p>{visible.length} 粒星</p></div>
 {visible.length?<div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><div className="image-wrap"><button className="bare-image" onClick={()=>setSelected(p)}><ProductImage product={p}/></button>{p.badge&&<span className="badge">{p.badge}</span>}<button className="quick-add" onClick={()=>add(p.id)} aria-label={`將${p.name}加落袋`}>＋</button></div><div className="product-info"><p className="category-label">{p.category}</p><button className="product-name" onClick={()=>setSelected(p)}><h3>{p.name}</h3></button><p>{p.description}</p><div><span><small>想像價</small><b>{money(p.price)}</b></span><span className="rating">★ {p.rating}</span></div></div></article>)}</div>:<div className="no-results"><span>☾</span><h3>呢個軌道暫時冇嘢</h3><p>試吓另一個關鍵字。</p><button className="primary" onClick={()=>{setQuery('');setCategory('全部')}}>睇返全部</button></div>}</section>
 <section className="story section" id="story"><div className="story-visual"><div className="big-moon">0<small>HKD</small></div><span className="orbit-line one">✦</span><span className="orbit-line two">☁</span></div><div><p className="eyebrow">The zero-gravity promise</p><h2>快樂有重量，<br/>付款冇可能。</h2><p>Little Orbit 係完全虛構嘅 BB 購物宇宙。你可以揀、可以加落袋，甚至可以「落單」——但我哋唔收錢、唔送貨，亦唔會問你攞真實地址。</p><ol><li><span>01</span><div><b>揀一粒星</b><small>睇中就加落購物袋。</small></div></li><li><span>02</span><div><b>假裝結帳</b><small>全宇宙自動減到 HK$0。</small></div></li><li><span>03</span><div><b>送到想像力</b><small>預計永遠唔會真正到達。</small></div></li></ol></div></section>
 <section className="faq section" id="faq"><div><p className="eyebrow">Orbit manual</p><h2>地球人常見問題</h2></div><div className="faq-list"><details><summary>呢度真係可以買嘢？<span>＋</span></summary><p>唔可以。產品、庫存同訂單全部虛構。</p></details><details><summary>會唔會扣錢？<span>＋</span></summary><p>永遠唔會。實際付款固定係 HK$0。</p></details><details><summary>需要地址或者信用卡？<span>＋</span></summary><p>唔需要，亦唔應該。我哋唔收敏感資料。</p></details><details><summary>資料會去邊？<span>＋</span></summary><p>購物袋只留喺你部裝置，隨時可以清除。</p></details></div></section></main>
 <footer><div className="footer-brand"><a className="logo" href="#top"><span className="logo-orbit"><i>✦</i></span><span>little orbit<small>小小宇宙</small></span></a><p>為小小日常，留一片大大星空。</p></div><div><b>探索</b><a href="#shop">所有產品</a><a href="#story">點解係 $0？</a></div><div><b>你嘅資料</b><button onClick={reset}>{t.clear}</button><small>全部只儲存喺呢部裝置。</small></div><span>© 2026 Little Orbit · Fictional from Hong Kong to the Moon</span></footer>
 {selected&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="product-modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setSelected(null)}>×</button><ProductImage product={selected}/><div className="product-modal-copy"><p className="eyebrow">{selected.category}</p><h2>{selected.name}</h2><p className="en-name">{selected.enName}</p><p>{selected.description}</p><div className="modal-price"><span><small>想像價</small><b>{money(selected.price)}</b></span><span>★ {selected.rating}</span></div><div className="fiction-note">✦ 純屬虛構產品，唔會真正出售或送到。</div><button className="primary" onClick={()=>{add(selected.id);setSelected(null)}}>加入想像購物袋 ＋</button></div></section></div>}
 {drawer&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setDrawer(false)}}><aside className="drawer" role="dialog" aria-modal="true"><div className="drawer-head"><div><p className="eyebrow">Your tiny orbit</p><h2>購物袋<span>{count}</span></h2></div><button ref={closeRef} className="close" onClick={()=>setDrawer(false)}>×</button></div><div className="cart-items">{items.length?items.map(p=><div className="cart-row" key={p.id}><ProductImage product={p}/><div><h3>{p.name}</h3><p>{money(p.price)}</p><div className="quantity"><button onClick={()=>update(p.id,-1)}>−</button><span>{p.quantity}</span><button onClick={()=>update(p.id,1)}>＋</button></div></div><button className="remove" onClick={()=>update(p.id,-p.quantity)}>×</button></div>):<div className="empty"><span>☾</span><h3>{t.empty}</h3><p>{t.emptySub}</p></div>}</div>{items.length>0&&<div className="cart-summary"><p className="cart-joke">☾ {t.disclaimer}</p><dl><div><dt>{t.subtotal}</dt><dd>{money(subtotal)}</dd></div><div className="discount"><dt>{t.discount}</dt><dd>−{money(subtotal)}</dd></div><div className="grand-total"><dt>{t.total}</dt><dd>{money(0)}</dd></div></dl><button className="primary checkout-button" onClick={()=>{setDrawer(false);setCheckout(true)}}>{t.checkout} →</button><small>唔使信用卡・唔使真實地址・真係唔使畀錢</small></div>}</aside></div>}
 {checkout&&<div className="modal-backdrop"><section className="checkout-modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setCheckout(false)}>×</button><p className="eyebrow">Zero-gravity checkout</p><h2>最後一步，繼續幻想。</h2><p className="checkout-intro">唔會問你攞電話、真實地址或者付款資料。</p><div className="checkout-box"><div><span>◉</span><p><small>虛構付款方式</small><b>ORBIT PASS •••• 0000</b></p><em>只供顯示</em></div></div><label className="district-label">想像送到邊區？（可選）<select value={district} onChange={e=>setDistrict(e.target.value)}><option value="">唔講都得</option><option>香港島</option><option>九龍</option><option>新界</option><option>離島</option><option>月球背面</option></select></label><label className="ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>{t.acknowledgement}</span></label><dl className="checkout-totals"><div><dt>{t.subtotal}</dt><dd>{money(subtotal)}</dd></div><div><dt>{t.discount}</dt><dd>−{money(subtotal)}</dd></div><div><dt>{t.total}</dt><dd>{money(PAYABLE_TOTAL)}</dd></div></dl><button className="primary order-button" disabled={!ack} onClick={finish}>{t.order}</button></section></div>}
 {complete&&<div className="modal-backdrop"><section className="success-modal" role="dialog" aria-modal="true" aria-labelledby="success-title"><div className="success-burst">✦</div><p className="eyebrow">Order in orbit</p><h2 id="success-title">落單成功！</h2><p>放心，冇任何錢離開過你。</p><div className="timeline">{deliveryStories[story].map((step,index)=><p className="done" key={step}><span>{index===0?'✓':index+1}</span>{step}</p>)}</div><button className="primary" onClick={()=>setComplete(false)}>再行一轉</button></section></div>}<div className={`toast ${toast?'show':''}`} role="status">{toast}</div></div>
}
